### ISSUE TITLE
NullReferenceException when running against .Net Core 3.0

### ISSUE THREAD

**Issue by alex6dj** [yallie/Zyanea#6]
When running against .Net Core 3.0 preview 6 it fail with a System.NullReferenceException, but in Net Core 2 it runs  ok.

StackTrace:
System.NullReferenceException
  HResult=0x80004003
  Mensaje = Object reference not set to an instance of an object.
  Origen = Hyperion
  Seguimiento de la pila:
   at Hyperion.Extensions.TypeEx.GetEmptyObject(Type type)
   at Hyperion.ValueSerializers.ObjectSerializer.ReadValue(Stream stream, DeserializerSession session)
   at Hyperion.Serializer.Deserialize[T](Stream stream)
   at Zyanea.ZyanServer.<HandleReceivedMessage>d__21.MoveNext() in E:\Projects\Zyanea\src\Zyanea\ZyanServer.cs:line 58

When running tests against net core 3 they get stuck.

**Comment by yallie** [comment]
Thanks for your observations!

Looks like Hyperion serializer doesn't yet support .NET Core 3.0 properly:
https://github.com/akkadotnet/Hyperion/issues/111

I'm not sure if it's the same issue, but it may be related.
